In [1]:
import pandas as pd

# Load data
xls2 = pd.ExcelFile("E:\\数学建模国赛2023选题\\C题\\附件2.xlsx")
df2=pd.read_excel(xls2)
df2

,销售日期,扫码销售时间,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售
0,2020-07-01,09:15:07.924,102900005117056,0.396,7.6,销售,否
1,2020-07-01,09:17:27.295,102900005115960,0.849,3.2,销售,否
2,2020-07-01,09:17:33.905,102900005117056,0.409,7.6,销售,否
3,2020-07-01,09:19:45.450,102900005115823,0.421,10.0,销售,否
4,2020-07-01,09:20:23.686,102900005115908,0.539,8.0,销售,否
...,...,...,...,...,...,...,...
878498,2023-06-30,21:35:13.264,102900005115250,0.284,24.0,销售,否
878499,2023-06-30,21:35:14.358,102900011022764,0.669,12.0,销售,否
878500,2023-06-30,21:35:20.264,102900005115250,0.125,24.0,销售,否
878501,2023-06-30,21:35:21.509,102900011016701,0.252,5.2,销售,否
878502,2023-06-30,21:40:48.248,102900011022764,0.803,12.0,销售,否

In [2]:
# Filter the data for the dates 2023-06-24 to 2023-06-30
# First, convert the '销售日期' column to datetime format
df2['销售日期'] = pd.to_datetime(df2['销售日期'])

# Filter the data for the specified date range
date_range_start = '2023-06-24'
date_range_end = '2023-06-30'
filtered_df = df2[(df2['销售日期'] >= date_range_start) & (df2['销售日期'] <= date_range_end)]

In [3]:
filtered_df

,销售日期,扫码销售时间,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售
875001,2023-06-24,09:10:47.276,102900011032022,1.000,2.8,销售,否
875002,2023-06-24,09:10:47.531,102900005115786,0.379,4.0,销售,否
875003,2023-06-24,09:13:51.795,102900005115762,0.505,4.0,销售,否
875004,2023-06-24,09:14:43.77,102900005115762,0.505,4.0,销售,否
875005,2023-06-24,09:14:44.044,102900011030059,1.000,4.5,销售,否
...,...,...,...,...,...,...,...
878498,2023-06-30,21:35:13.264,102900005115250,0.284,24.0,销售,否
878499,2023-06-30,21:35:14.358,102900011022764,0.669,12.0,销售,否
878500,2023-06-30,21:35:20.264,102900005115250,0.125,24.0,销售,否
878501,2023-06-30,21:35:21.509,102900011016701,0.252,5.2,销售,否
878502,2023-06-30,21:40:48.248,102900011022764,0.803,12.0,销售,否

In [4]:
# Show some basic statistics to confirm the filter
filtered_df.describe(include='all', datetime_is_numeric=True)

,销售日期,扫码销售时间,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售
count,3502,3502,3.502000e+03,3502.000000,3502.000000,3502,3502
unique,NaN,3502,NaN,NaN,NaN,1,2
top,NaN,09:10:47.276,NaN,NaN,NaN,销售,否
freq,NaN,1,NaN,NaN,NaN,3502,3123
mean,2023-06-27 00:07:48.760707840,NaN,1.031028e+14,0.596575,8.084752,NaN,NaN
min,2023-06-24 00:00:00,NaN,1.029000e+14,0.038000,1.200000,NaN,NaN
25%,2023-06-25 00:00:00,NaN,1.029000e+14,0.327000,4.500000,NaN,NaN
50%,2023-06-27 00:00:00,NaN,1.029000e+14,0.485000,5.800000,NaN,NaN
75%,2023-06-29 00:00:00,NaN,1.029000e+14,1.000000,11.200000,NaN,NaN
max,2023-06-30 00:00:00,NaN,1.069715e+14,2.242000,26.000000,NaN,NaN
std,NaN,NaN,8.841871e+11,0.321443,5.904332,NaN,NaN

In [5]:
df2=filtered_df
df2

,销售日期,扫码销售时间,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售
875001,2023-06-24,09:10:47.276,102900011032022,1.000,2.8,销售,否
875002,2023-06-24,09:10:47.531,102900005115786,0.379,4.0,销售,否
875003,2023-06-24,09:13:51.795,102900005115762,0.505,4.0,销售,否
875004,2023-06-24,09:14:43.77,102900005115762,0.505,4.0,销售,否
875005,2023-06-24,09:14:44.044,102900011030059,1.000,4.5,销售,否
...,...,...,...,...,...,...,...
878498,2023-06-30,21:35:13.264,102900005115250,0.284,24.0,销售,否
878499,2023-06-30,21:35:14.358,102900011022764,0.669,12.0,销售,否
878500,2023-06-30,21:35:20.264,102900005115250,0.125,24.0,销售,否
878501,2023-06-30,21:35:21.509,102900011016701,0.252,5.2,销售,否
878502,2023-06-30,21:40:48.248,102900011022764,0.803,12.0,销售,否

In [6]:
#filtered_df.to_excel("E:\\数学建模国赛2023选题\\C题\\df2.3（为第三题准备的）.xlsx", index=True)

In [7]:
xls1 = pd.ExcelFile("E:\\数学建模国赛2023选题\\C题\\附件1.xlsx")
df1=pd.read_excel(xls1)
df1

                单品编码        单品名称        分类编码 分类名称
0    102900005115168        牛首生菜  1011010101  花叶类
1    102900005115199       四川红香椿  1011010101  花叶类
2    102900005115625      本地小毛白菜  1011010101  花叶类
3    102900005115748         白菜苔  1011010101  花叶类
4    102900005115762          苋菜  1011010101  花叶类
..               ...         ...         ...  ...
246  106958851400125   海鲜菇(袋)(4)  1011010801  食用菌
247  106971533450003      海鲜菇(包)  1011010801  食用菌
248  106971533455008   海鲜菇(袋)(3)  1011010801  食用菌
249  106973223300667   虫草花(盒)(2)  1011010801  食用菌
250  106973990980123  和丰阳光海鲜菇(包)  1011010801  食用菌

[251 rows x 4 columns]

In [8]:
xls3 = pd.ExcelFile("E:\\数学建模国赛2023选题\\C题\\附件3.xlsx")
df3=pd.read_excel(xls3)
df3

              日期             单品编码  批发价格(元/千克)
0     2020-07-01  102900005115762        3.88
1     2020-07-01  102900005115779        6.72
2     2020-07-01  102900005115786        3.19
3     2020-07-01  102900005115793        9.24
4     2020-07-01  102900005115823        7.03
...          ...              ...         ...
55977 2023-06-30  102900051000944       18.00
55978 2023-06-30  102900051004294        6.45
55979 2023-06-30  102900051010455        4.48
55980 2023-06-30  106949711300259        1.45
55981 2023-06-30  106971533450003        1.95

[55982 rows x 3 columns]

In [9]:
df3['日期'] = pd.to_datetime(df3['日期'])

# Filter the data for the specified date range
date_range_start = '2023-06-24'
date_range_end = '2023-06-30'
df3 = df3[(df3['日期'] >= date_range_start) & (df3['日期'] <= date_range_end)]
df3

              日期             单品编码  批发价格(元/千克)
55628 2023-06-24  102900005115250       15.60
55629 2023-06-24  102900005115762        2.31
55630 2023-06-24  102900005115779        5.75
55631 2023-06-24  102900005115786        2.41
55632 2023-06-24  102900005115823        4.32
...          ...              ...         ...
55977 2023-06-30  102900051000944       18.00
55978 2023-06-30  102900051004294        6.45
55979 2023-06-30  102900051010455        4.48
55980 2023-06-30  106949711300259        1.45
55981 2023-06-30  106971533450003        1.95

[354 rows x 3 columns]

In [10]:
#df3.to_excel("E:\\数学建模国赛2023选题\\C题\\df3（为第三题准备的）.xlsx", index=True)

In [11]:
import pandas as pd

# Load the Excel file
file_path4 = ("E:\\数学建模国赛2023选题\\C题\\附件4.xlsx")

# Check the sheet names first to understand the structure of the Excel file
sheet_names = pd.ExcelFile(file_path4).sheet_names
sheet_names

['平均损耗率(%)_小分类编码_不同值', 'Sheet1']

In [12]:
df4 = pd.read_excel(file_path4, sheet_name=sheet_names[1])

In [13]:
df4

                单品编码        单品名称  损耗率(%)
0    102900005115168        牛首生菜    4.39
1    102900005115199       四川红香椿   10.46
2    102900005115250     西峡花菇(1)   10.80
3    102900005115625      本地小毛白菜    0.18
4    102900005115748         白菜苔    8.78
..               ...         ...     ...
246  106971533455008   海鲜菇(袋)(3)    1.30
247  106971563780002   鲜粽叶(袋)(2)    0.00
248  106972776821582   鲜粽叶(袋)(3)    9.43
249  106973223300667   虫草花(盒)(2)   11.13
250  106973990980123  和丰阳光海鲜菇(包)    0.12

[251 rows x 3 columns]

In [14]:
merged_df = pd.merge(df2, df1, on='单品编码', how='left')
merged_df = pd.merge(merged_df, df3, left_on=['单品编码', '销售日期'], right_on=['单品编码', '日期'], how='left')
merged_df = pd.merge(merged_df, df4, on='单品编码', how='left')
merged_df

,销售日期,扫码销售时间,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售,单品名称_x,分类编码,分类名称,日期,批发价格(元/千克),单品名称_y,损耗率(%)
0,2023-06-24,09:10:47.276,102900011032022,1.000,2.8,销售,否,小皱皮(份),1011010504,辣椒类,2023-06-24,1.51,小皱皮(份),9.43
1,2023-06-24,09:10:47.531,102900005115786,0.379,4.0,销售,否,竹叶菜,1011010101,花叶类,2023-06-24,2.41,竹叶菜,13.62
2,2023-06-24,09:13:51.795,102900005115762,0.505,4.0,销售,否,苋菜,1011010101,花叶类,2023-06-24,2.31,苋菜,18.52
3,2023-06-24,09:14:43.77,102900005115762,0.505,4.0,销售,否,苋菜,1011010101,花叶类,2023-06-24,2.31,苋菜,18.52
4,2023-06-24,09:14:44.044,102900011030059,1.000,4.5,销售,否,云南生菜(份),1011010101,花叶类,2023-06-24,3.32,云南生菜(份),9.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3497,2023-06-30,21:35:13.264,102900005115250,0.284,24.0,销售,否,西峡花菇(1),1011010801,食用菌,2023-06-30,15.60,西峡花菇(1),10.80
3498,2023-06-30,21:35:14.358,102900011022764,0.669,12.0,销售,否,长线茄,1011010501,茄类,2023-06-30,7.00,长线茄,6.90
3499,2023-06-30,21:35:20.264,102900005115250,0.125,24.0,销售,否,西峡花菇(1),1011010801,食用菌,2023-06-30,15.60,西峡花菇(1),10.80
3500,2023-06-30,21:35:21.509,102900011016701,0.252,5.2,销售,否,芜湖青椒(1),1011010504,辣椒类,2023-06-30,3.63,芜湖青椒(1),5.70
3501,2023-06-30,21:40:48.248,102900011022764,0.803,12.0,销售,否,长线茄,1011010501,茄类,2023-06-30,7.00,长线茄,6.90

In [27]:
columns_to_drop = ['扫码销售时间', '分类编码', '分类名称', '日期']
merged_df = merged_df.drop(columns=columns_to_drop, errors='ignore')

In [28]:
merged_df

,销售日期,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售,单品名称_x,批发价格(元/千克),单品名称_y,损耗率(%)
0,2023-06-24,102900011032022,1.000,2.8,销售,否,小皱皮(份),1.51,小皱皮(份),9.43
1,2023-06-24,102900005115786,0.379,4.0,销售,否,竹叶菜,2.41,竹叶菜,13.62
2,2023-06-24,102900005115762,0.505,4.0,销售,否,苋菜,2.31,苋菜,18.52
3,2023-06-24,102900005115762,0.505,4.0,销售,否,苋菜,2.31,苋菜,18.52
4,2023-06-24,102900011030059,1.000,4.5,销售,否,云南生菜(份),3.32,云南生菜(份),9.43
...,...,...,...,...,...,...,...,...,...,...
3497,2023-06-30,102900005115250,0.284,24.0,销售,否,西峡花菇(1),15.60,西峡花菇(1),10.80
3498,2023-06-30,102900011022764,0.669,12.0,销售,否,长线茄,7.00,长线茄,6.90
3499,2023-06-30,102900005115250,0.125,24.0,销售,否,西峡花菇(1),15.60,西峡花菇(1),10.80
3500,2023-06-30,102900011016701,0.252,5.2,销售,否,芜湖青椒(1),3.63,芜湖青椒(1),5.70
3501,2023-06-30,102900011022764,0.803,12.0,销售,否,长线茄,7.00,长线茄,6.90

In [29]:
# Merge the '单品名称_x' and '单品名称_y' columns into one '单品名称' column
# If '单品名称_x' is missing, use '单品名称_y', otherwise use '单品名称_x'
merged_df['单品名称'] = merged_df.apply(lambda row: row['单品名称_x'] if pd.notna(row['单品名称_x']) else row['单品名称_y'], axis=1)

# Drop the '单品名称_x' and '单品名称_y' columns as they are now redundant
merged_df.drop(columns=['单品名称_x', '单品名称_y'], inplace=True)

# Show the first few rows of the DataFrame with the integrated '单品名称' column
merged_df.head()

,销售日期,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售,批发价格(元/千克),损耗率(%),单品名称
0,2023-06-24,102900011032022,1.000,2.8,销售,否,1.51,9.43,小皱皮(份)
1,2023-06-24,102900005115786,0.379,4.0,销售,否,2.41,13.62,竹叶菜
2,2023-06-24,102900005115762,0.505,4.0,销售,否,2.31,18.52,苋菜
3,2023-06-24,102900005115762,0.505,4.0,销售,否,2.31,18.52,苋菜
4,2023-06-24,102900011030059,1.000,4.5,销售,否,3.32,9.43,云南生菜(份)

In [30]:
merged_df

,销售日期,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售,批发价格(元/千克),损耗率(%),单品名称
0,2023-06-24,102900011032022,1.000,2.8,销售,否,1.51,9.43,小皱皮(份)
1,2023-06-24,102900005115786,0.379,4.0,销售,否,2.41,13.62,竹叶菜
2,2023-06-24,102900005115762,0.505,4.0,销售,否,2.31,18.52,苋菜
3,2023-06-24,102900005115762,0.505,4.0,销售,否,2.31,18.52,苋菜
4,2023-06-24,102900011030059,1.000,4.5,销售,否,3.32,9.43,云南生菜(份)
...,...,...,...,...,...,...,...,...,...
3497,2023-06-30,102900005115250,0.284,24.0,销售,否,15.60,10.80,西峡花菇(1)
3498,2023-06-30,102900011022764,0.669,12.0,销售,否,7.00,6.90,长线茄
3499,2023-06-30,102900005115250,0.125,24.0,销售,否,15.60,10.80,西峡花菇(1)
3500,2023-06-30,102900011016701,0.252,5.2,销售,否,3.63,5.70,芜湖青椒(1)
3501,2023-06-30,102900011022764,0.803,12.0,销售,否,7.00,6.90,长线茄

In [32]:
# Perform statistical descriptive analysis on the final merged DataFrame
merged_df.describe(include='all', datetime_is_numeric=True)

,销售日期,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售,批发价格(元/千克),损耗率(%),单品名称
count,3502,3.502000e+03,3502.000000,3502.000000,3502,3502,3502.000000,3502.000000,3502
unique,NaN,NaN,NaN,NaN,1,2,NaN,NaN,49
top,NaN,NaN,NaN,NaN,销售,否,NaN,NaN,芜湖青椒(1)
freq,NaN,NaN,NaN,NaN,3502,3123,NaN,NaN,272
mean,2023-06-27 00:07:48.760707840,1.031028e+14,0.596575,8.084752,NaN,NaN,5.382818,9.762924,NaN
min,2023-06-24 00:00:00,1.029000e+14,0.038000,1.200000,NaN,NaN,1.210000,0.000000,NaN
25%,2023-06-25 00:00:00,1.029000e+14,0.327000,4.500000,NaN,NaN,2.600000,6.757500,NaN
50%,2023-06-27 00:00:00,1.029000e+14,0.485000,5.800000,NaN,NaN,3.490000,9.430000,NaN
75%,2023-06-29 00:00:00,1.029000e+14,1.000000,11.200000,NaN,NaN,7.420000,10.800000,NaN
max,2023-06-30 00:00:00,1.069715e+14,2.242000,26.000000,NaN,NaN,18.000000,29.250000,NaN
std,NaN,8.841871e+11,0.321443,5.904332,NaN,NaN,4.203260,5.325999,NaN

In [33]:
# Drop the '销售类型' column from the cleaned DataFrame
merged_df.drop(columns=['销售类型'], inplace=True, errors='ignore')

# Show the first few rows of the DataFrame after dropping the '销售类型' column
merged_df.head()

,销售日期,单品编码,销量(千克),销售单价(元/千克),是否打折销售,批发价格(元/千克),损耗率(%),单品名称
0,2023-06-24,102900011032022,1.000,2.8,否,1.51,9.43,小皱皮(份)
1,2023-06-24,102900005115786,0.379,4.0,否,2.41,13.62,竹叶菜
2,2023-06-24,102900005115762,0.505,4.0,否,2.31,18.52,苋菜
3,2023-06-24,102900005115762,0.505,4.0,否,2.31,18.52,苋菜
4,2023-06-24,102900011030059,1.000,4.5,否,3.32,9.43,云南生菜(份)

In [35]:
# Calculate the proportion of sales that are discounted ('是')
discounted_sales_count = merged_df[merged_df['是否打折销售'] == '是'].shape[0]
total_sales_count = merged_df.shape[0]

# Calculate the proportion
discounted_sales_proportion = discounted_sales_count / total_sales_count * 100

discounted_sales_proportion

10.822387207310108

In [37]:
# Drop the '单品编码' column from the cleaned DataFrame
merged_df.drop(columns=['单品编码'], inplace=True, errors='ignore')

# Show the first few rows of the DataFrame after dropping the '单品编码' column
merged_df

           销售日期  销量(千克)  销售单价(元/千克) 是否打折销售  批发价格(元/千克)  损耗率(%)     单品名称
0    2023-06-24   1.000         2.8      否        1.51    9.43   小皱皮(份)
1    2023-06-24   0.379         4.0      否        2.41   13.62      竹叶菜
2    2023-06-24   0.505         4.0      否        2.31   18.52       苋菜
3    2023-06-24   0.505         4.0      否        2.31   18.52       苋菜
4    2023-06-24   1.000         4.5      否        3.32    9.43  云南生菜(份)
...         ...     ...         ...    ...         ...     ...      ...
3497 2023-06-30   0.284        24.0      否       15.60   10.80  西峡花菇(1)
3498 2023-06-30   0.669        12.0      否        7.00    6.90      长线茄
3499 2023-06-30   0.125        24.0      否       15.60   10.80  西峡花菇(1)
3500 2023-06-30   0.252         5.2      否        3.63    5.70  芜湖青椒(1)
3501 2023-06-30   0.803        12.0      否        7.00    6.90      长线茄

[3502 rows x 7 columns]

In [38]:
#merged_df.to_excel("E:\\数学建模国赛2023选题\\C题\\第三题数据表格.xlsx", index=True)

In [15]:
# Calculate the total sales weight and total sales amount for each product
demand_analysis = merged_df.groupby('单品编码').agg({
    '销量(千克)': 'sum',
    '销售单价(元/千克)': 'mean'  # Taking mean as the price might vary
}).reset_index()

# Calculate total sales amount
demand_analysis['总销售额(元)'] = demand_analysis['销量(千克)'] * demand_analysis['销售单价(元/千克)']

# Sort the products by total sales weight and total sales amount
demand_analysis_sorted_by_weight = demand_analysis.sort_values(by='销量(千克)', ascending=False)
demand_analysis_sorted_by_amount = demand_analysis.sort_values(by='总销售额(元)', ascending=False)

# Display the top 10 products by total sales weight and total sales amount
top_10_by_weight = demand_analysis_sorted_by_weight.head(10)
top_10_by_amount = demand_analysis_sorted_by_amount.head(10)

top_10_by_weight

               单品编码   销量(千克)  销售单价(元/千克)      总销售额(元)
26  102900011030059  226.000    4.461504  1008.300000
30  102900011031100  150.000    5.769333   865.400000
27  102900011030097  149.000    4.159060   619.700000
47  106949711300259  113.000    1.879646   212.400000
22  102900011016701   99.634    5.200000   518.096800
3   102900005115786   93.077    3.773953   351.268269
10  102900005116714   87.904   12.408040  1090.716366
34  102900011032251   79.000    4.922785   388.900000
32  102900011032022   79.000    2.586076   204.300000
8   102900005116257   76.320    6.000000   457.920000

In [16]:
top_10_by_amount

               单品编码   销量(千克)  销售单价(元/千克)      总销售额(元)
10  102900005116714   87.904   12.408040  1090.716366
26  102900011030059  226.000    4.461504  1008.300000
30  102900011031100  150.000    5.769333   865.400000
0   102900005115250   32.369   24.000000   776.856000
27  102900011030097  149.000    4.159060   619.700000
11  102900005116899   42.184   14.400000   607.449600
46  102900051000944   28.232   20.090909   567.206545
16  102900011000328   47.897   11.291339   540.821244
22  102900011016701   99.634    5.200000   518.096800
14  102900005118831   73.000    6.541096   477.500000

In [17]:
# Calculate the average wholesale price for each product
supply_analysis = merged_df.groupby('单品编码').agg({
    '批发价格(元/千克)': 'mean'
}).reset_index()

# Merge with the demand analysis data to get a complete view
complete_analysis = pd.merge(demand_analysis, supply_analysis, on='单品编码', how='inner')

# Add a profit margin column (Sales Price - Wholesale Price)
complete_analysis['毛利润(元/千克)'] = complete_analysis['销售单价(元/千克)'] - complete_analysis['批发价格(元/千克)']

# Sort the products by profit margin
complete_analysis_sorted_by_profit = complete_analysis.sort_values(by='毛利润(元/千克)', ascending=False)

# Display the top 10 products by profit margin
top_10_by_profit = complete_analysis_sorted_by_profit.head(10)

top_10_by_profit

               单品编码  销量(千克)  销售单价(元/千克)      总销售额(元)  批发价格(元/千克)  毛利润(元/千克)
23  102900011018132   2.439   26.000000    63.414000   16.066667   9.933333
0   102900005115250  32.369   24.000000   776.856000   15.600000   8.400000
35  102900011032343   7.302   18.986667   138.640640   12.274667   6.712000
42  102900011035078  14.250   18.892308   269.215385   12.973231   5.919077
24  102900011022764  29.501   12.000000   354.012000    6.984932   5.015068
17  102900011001691  12.224   14.000000   171.136000    9.168696   4.831304
38  102900011033982   1.024    9.000000     9.216000    4.340000   4.660000
10  102900005116714  87.904   12.408040  1090.716366    7.772965   4.635075
12  102900005118817   6.820   14.000000    95.480000    9.635294   4.364706
18  102900011006948   6.538   12.514286    81.818400    8.241429   4.272857

In [20]:
# Filter the data to get the unique products available for sale during the date range 2023-06-24 to 2023-06-30
available_products = merged_df.drop_duplicates(subset=['单品编码'])
available_products

,销售日期,扫码销售时间,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售,单品名称_x,分类编码,分类名称,日期,批发价格(元/千克),单品名称_y,损耗率(%)
0,2023-06-24,09:10:47.276,102900011032022,1.000,2.8,销售,否,小皱皮(份),1011010504,辣椒类,2023-06-24,1.51,小皱皮(份),9.43
1,2023-06-24,09:10:47.531,102900005115786,0.379,4.0,销售,否,竹叶菜,1011010101,花叶类,2023-06-24,2.41,竹叶菜,13.62
2,2023-06-24,09:13:51.795,102900005115762,0.505,4.0,销售,否,苋菜,1011010101,花叶类,2023-06-24,2.31,苋菜,18.52
4,2023-06-24,09:14:44.044,102900011030059,1.000,4.5,销售,否,云南生菜(份),1011010101,花叶类,2023-06-24,3.32,云南生菜(份),9.43
6,2023-06-24,09:19:55.484,102900005115823,0.477,8.0,销售,否,上海青,1011010101,花叶类,2023-06-24,4.32,上海青,14.43
7,2023-06-24,09:19:55.705,102900011006948,0.485,12.0,销售,否,外地茼蒿,1011010101,花叶类,2023-06-24,7.66,外地茼蒿,26.16
8,2023-06-24,09:22:36.474,102900005115250,0.271,24.0,销售,否,西峡花菇(1),1011010801,食用菌,2023-06-24,15.60,西峡花菇(1),10.80
9,2023-06-24,09:25:27.795,102900051000463,0.415,8.0,销售,否,圆茄子(2),1011010501,茄类,2023-06-24,5.38,圆茄子(2),6.71
10,2023-06-24,09:26:23.77,102900011016701,0.426,5.2,销售,否,芜湖青椒(1),1011010504,辣椒类,2023-06-24,2.83,芜湖青椒(1),5.70
11,2023-06-24,09:27:30.513,102900011030097,1.000,4.5,销售,否,云南油麦菜(份),1011010101,花叶类,2023-06-24,2.94,云南油麦菜(份),9.43
14,2023-06-24,09:29:11.705,102900011035078,0.250,20.0,销售,否,红椒(2),1011010504,辣椒类,2023-06-24,13.46,红椒(2),9.43
16,2023-06-24,09:29:39.092,106971533450003,1.000,3.0,销售,否,海鲜菇(包),1011010801,食用菌,2023-06-24,1.95,海鲜菇(包),0.00
17,2023-06-24,09:31:00.858,102900005116714,0.373,14.0,销售,否,西兰花,1011010201,花菜类,2023-06-24,8.42,西兰花,9.26
19,2023-06-24,09:31:43.194,102900005116899,0.576,16.0,销售,否,净藕(1),1011010402,水生根茎类,2023-06-24,11.00,净藕(1),5.54
24,2023-06-24,09:33:16.728,102900011031100,1.000,5.8,销售,否,小米椒(份),1011010504,辣椒类,2023-06-24,2.36,小米椒(份),9.43
25,2023-06-24,09:33:26.05,102900005119975,0.269,6.0,销售,否,红薯尖,1011010101,花叶类,2023-06-24,3.60,红薯尖,8.42
26,2023-06-24,09:33:32.678,102900005116257,0.285,6.0,销售,否,紫茄子(2),1011010501,茄类,2023-06-24,3.80,紫茄子(2),6.07
28,2023-06-24,09:33:41.958,102900011034026,0.594,14.0,销售,否,枝江青梗散花,1011010201,花菜类,2023-06-24,9.89,枝江青梗散花,9.43
31,2023-06-24,09:34:20.181,102900011008164,0.291,5.2,销售,否,奶白菜,1011010101,花叶类,2023-06-24,2.40,奶白菜,15.68
39,2023-06-24,09:36:38.061,102900005115908,0.453,6.0,销售,否,菜心,1011010101,花叶类,2023-06-24,4.60,菜心,13.70
48,2023-06-24,09:41:39.061,102900005118831,1.000,4.1,销售,是,娃娃菜,1011010101,花叶类,2023-06-24,4.75,娃娃菜,2.48
55,2023-06-24,09:44:41.78,102900011031926,1.000,3.8,销售,否,虫草花(份),1011010801,食用菌,2023-06-24,2.66,虫草花(份),9.43
62,2023-06-24,09:45:59.18,102900011022764,0.151,12.0,销售,否,长线茄,1011010501,茄类,2023-06-24,6.94,长线茄,6.90
66,2023-06-24,09:50:08.686,106949711300259,1.000,2.0,销售,否,金针菇(盒),1011010801,食用菌,2023-06-24,1.45,金针菇(盒),0.45
74,2023-06-24,09:53:46.138,102900011023464,0.407,5.2,销售,否,小青菜(1),1011010101,花叶类,2023-06-24,3.00,小青菜(1),10.33
79,2023-06-24,09:56:18.547,102900005115946,0.336,6.0,销售,否,木耳菜,1011010101,花叶类,2023-06-24,3.25,木耳菜,7.61
80,2023-06-24,09:57:13.639,102900011034330,1.000,5.5,销售,否,双孢菇(盒),1011010801,食用菌,2023-06-24,3.39,双孢菇(盒),0.20
81,2023-06-24,09:58:08.966,102900005118824,0.432,16.0,销售,否,高瓜(1),1011010402,水生根茎类,2023-06-24,11.14,高瓜(1),29.25
84,2023-06-24,10:00:36.436,102900051000944,0.593,26.0,销售,否,洪湖藕带,1011010402,水生根茎类,2023-06-24,18.00,洪湖藕带,24.05
90,2023-06-24,10:04:56.109,102900005116509,0.470,6.0,销售,否,青茄子(1),1011010501,茄类,2023-06-24,4.12,青茄子(1),5.01
96,2023-06-24,10:05:38.965,102900011032251,1.000,3.9,销售,否,螺丝椒(份),1011010504,辣椒类,2023-06-24,2.78,螺丝椒(份),9.43
101,2023-06-24,10:09:38.233,102900011000328,0.462,10.0,销售,否,螺丝椒,1011010504,辣椒类,2023-06-24,6.24,螺丝椒,10.18
122,2023-06-24,10:23:13.264,102900005118817,0.358,14.0,销售,否,菠菜,1011010101,花叶类,2023-06-24,9.63,菠菜,18.51
136,2023-06-24,10:30:44.826,102900011035740,1.000,5.8,销售,否,蟹味菇与白玉菇双拼(盒),1011010801,食用菌,2023-06-24,3.16,蟹味菇与白玉菇双拼(盒),0.84
140,2023-06-24,10:31:47.186,102900011001691,0.330,14.0,销售,否,菱角,1011010402,水生根茎类,2023-06-24,9.19,菱角,9.61
159,2023-06-24,10:40:16.553,102900011032848,1.000,4.8,销售,否,姜蒜小米椒组合装(小份),1011010504,辣椒类,2023-06-24,2.63,姜蒜小米椒组合装(小份),9.43
214,2023-06-24,11:14:55.841,102900011032343,0.197,19.8,销售,否,七彩椒(2),1011010504,辣椒类,2023-06-24,11.92,七彩椒(2),9.43
318,2023-06-24,13:34:30.311,102900011030110,1.000,5.8,销售,否,菠菜(份),1011010101,花叶类,2023-06-24,3.90,菠菜(份),9.43
353,2023-06-24,15:18:03.19,102900011007969,0.240,9.2,销售,否,红莲藕带,1011010402,水生根茎类,2023-06-24,5.68,红莲藕带,16.63
380,2023-06-24,16:17:20.983,102900011034439,1.000,5.8,销售,否,青红杭椒组合装(份),1011010504,辣椒类,2023-06-24,3.53,青红杭椒组合装(份),9.43
384,2023-06-24,16:24:36.364,102900011032237,1.000,4.8,销售,否,青线椒(份),1011010504,辣椒类,2023-06-24,3.11,青线椒(份),9.43
631,2023-06-25,09:27:16.172,102900005115984,0.545,7.2,销售,否,云南油麦菜,1011010101,花叶类,2023-06-25,4.48,云南油麦菜,12.81
650,2023-06-25,09:47:12.264,102900011032732,0.261,18.0,销售,否,高瓜(2),1011010402,水生根茎类,2023-06-25,13.23,高瓜(2),9.43
708,2023-06-25,10:42:46.394,102900005115779,0.240,9.2,销售,否,云南生菜,1011010101,花叶类,2023-06-25,5.76,云南生菜,15.25
1170,2023-06-26,10:44:25.248,102900011013274,1.000,7.8,销售,否,白玉菇(袋),1011010801,食用菌,2023-06-26,3.58,白玉菇(袋),6.57
1353,2023-06-26,18:18:15.913,102900011030929,1.000,2.6,销售,是,鲜木耳(份),1011010801,食用菌,2023-06-26,1.30,鲜木耳(份),9.43
1532,2023-06-27,09:59:22.701,102900011018132,0.397,26.0,销售,否,野生粉藕,1011010402,水生根茎类,2023-06-27,16.07,野生粉藕,12.69
1713,2023-06-27,16:45:44.134,102900011033982,0.512,9.0,销售,否,紫茄子(1),1011010501,茄类,2023-06-27,4.34,紫茄子(1),9.43
1914,2023-06-27,20:48:10.998,102900011036686,1.000,3.9,销售,是,木耳菜(份),1011010101,花叶类,2023-06-27,1.46,木耳菜(份),9.43

In [19]:
# Count the number of available products
num_available_products = available_products.shape[0]

# Show the first few rows of available products and the total number
available_products.head(), num_available_products

(        销售日期        扫码销售时间             单品编码  销量(千克)  销售单价(元/千克) 销售类型 是否打折销售  \
 0 2023-06-24  09:10:47.276  102900011032022   1.000         2.8   销售      否
 1 2023-06-24  09:10:47.531  102900005115786   0.379         4.0   销售      否
 2 2023-06-24  09:13:51.795  102900005115762   0.505         4.0   销售      否
 4 2023-06-24  09:14:44.044  102900011030059   1.000         4.5   销售      否
 6 2023-06-24  09:19:55.484  102900005115823   0.477         8.0   销售      否

     单品名称_x        分类编码 分类名称         日期  批发价格(元/千克)   单品名称_y  损耗率(%)
 0   小皱皮(份)  1011010504  辣椒类 2023-06-24        1.51   小皱皮(份)    9.43
 1      竹叶菜  1011010101  花叶类 2023-06-24        2.41      竹叶菜   13.62
 2       苋菜  1011010101  花叶类 2023-06-24        2.31       苋菜   18.52
 4  云南生菜(份)  1011010101  花叶类 2023-06-24        3.32  云南生菜(份)    9.43
 6      上海青  1011010101  花叶类 2023-06-24        4.32      上海青   14.43  ,
 49)